GET http://localhost:8080/api/branches

###
GET http://localhost:8080/api/branches/2

###
POST http://localhost:8080/api/branches
Content-Type: application/json

{
  "name": "fries"
}

###
PUT http://localhost:8080/api/branches/2
Content-Type: application/json

{
  "name": "fries"
}

###
DELETE http://localhost:8080/api/branches/1

###
GET http://localhost:8080/api/branches/3/categories
###
GET http://localhost:8080/api/branches/3/categories/4

###
POST http://localhost:8080/api/branches/3/categories
Content-Type: application/json

{
  "name": "phones"
}

###

PUT http://localhost:8080/api/branches/1/categories/4
Content-Type: application/json

{
  "name": "computers"
}

###

DELETE http://localhost:8080/api/branches/1/categories/2

###

POST http://localhost:8080/api/branches/1/categories/3/auctions
Content-Type: application/json

{
  "name": "phone",
  "price": 20
}

###
PUT http://localhost:8080/api/branches/1/categories/2/auctions/1
Content-Type: application/json

{
  "name": "computer",
  "price": 300
}

###
DELETE http://localhost:8080/api/branches/1/categories/2/auctions/1

###