POST http://localhost:8080/api/branches
Content-Type: application/json

{
  "name": "fries"
}

###
PUT http://localhost:8080/api/branches/1
Content-Type: application/json

{
  "name": "fries"
}

###
DELETE http://localhost:8080/api/branches/1

###
POST http://localhost:8080/api/branches/1/categories
Content-Type: application/json

{
  "name": "phones"
}

###

PUT http://localhost:8080/api/branches/1/categories/2
Content-Type: application/json

{
  "name": "computers"
}

###

DELETE http://localhost:8080/api/branches/1/categories/2

###