GET http://localhost:8080/api/branches
Authorization: Basic WXVyaTp1c2Vy

###
GET http://localhost:8080/api/branches/2

###
POST http://localhost:8080/api/branches
Authorization: Basic SmF4OmFkbWlu
Content-Type: application/json

{
  "name": "fries"
}

###
PUT http://localhost:8080/api/branches/2
Content-Type: application/json

{
  "name": "fries"
}

###
DELETE http://localhost:8080/api/branches/4

###
GET http://localhost:8080/api/branches/3/categories

###
GET http://localhost:8080/api/branches/3/categories/4

###
POST http://localhost:8080/api/branches/3/categories
Content-Type: application/json

{
  "name": "phones"
}

###

PUT http://localhost:8080/api/branches/1/categories/4
Content-Type: application/json

{
  "name": "computers"
}

###

DELETE http://localhost:8080/api/branches/1/categories/2

###

POST http://localhost:8080/api/branches/1/categories/3/auctions
Content-Type: application/json

{
  "name": "phone",
  "price": 20,
  "quantity": 4
}

###
PUT http://localhost:8080/api/branches/1/categories/3/auctions/1
Content-Type: application/json

{
  "name": "pc",
  "price": 300,
  "quantity": 3
}

###
DELETE http://localhost:8080/api/branches/1/categories/2/auctions/2

###
GET http://localhost:8080/api/branches/1/categories/3/auctions/2

###
POST http://localhost:8080/api/users/
Content-Type: application/json

{
  "login": "Jax"
}

###error because it's id for now
PUT http://localhost:8080/api/users/Jax
Content-Type: application/json

{
  "login": "Pantheon"
}

###

GET http://localhost:8080/api/users

###
GET http://localhost:8080/api/users/Jax

###

GET http://localhost:8080/api/users/Jax/orders/1

###
DELETE http://localhost:8080/api/users/Jax

###
POST http://localhost:8080/api/users/Jax/orders
Content-Type: application/json

{
  "items": [
    {
      "auctionId": 1,
      "quantity": 4
    },
    {
      "auctionId": 2,
      "quantity": 3
    }
  ]
}

###
POST http://localhost:8080/api/users/Jax/basket/items/
Content-Type: application/json

{
  "auctionId": 1,
  "quantity": 2
}

###
GET http://localhost:8080/api/users/Jax/basket/items/

###
POST http://localhost:8080/api/users/Jax/basket/items/
Content-Type: application/json

{
  "auctionId": 2,
  "quantity": 2
}
###
POST http://localhost:8080/api/users/Jax/basket/items/
Content-Type: application/json

{
  "auctionId": 3,
  "quantity": 2
}
###

PUT http://localhost:8080/api/users/Jax/basket/items/1
Content-Type: application/json

{
  "quantity": 1
}

###
DELETE http://localhost:8080/api/users/Jax/basket/items/2
Content-Type: application/json
